# Generated by Django 3.2.5 on 2021-07-22 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210721_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(upload_to='photo/%Y/%m/%d/'),
        ),
    ]
